/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/source-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Images
         * @description List source images with pagination and optional filtering.
         */
        get: operations["list_source_images_source_images_get"];
        put?: never;
        /**
         * Create Source Image
         * @description Create a new source image record.
         */
        post: operations["create_source_image_source_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Image
         * @description Get a single source image by ID.
         */
        get: operations["get_source_image_source_images__id__get"];
        /**
         * Update Source Image
         * @description Update a source image.
         */
        put: operations["update_source_image_source_images__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-images/recalculate-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalculate Usage Counts
         * @description Recalculate all usage counts from actual ImageSlot references.
         */
        post: operations["recalculate_usage_counts_source_images_recalculate_usage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-images/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Image Tags
         * @description Get all tags for a source image.
         */
        get: operations["get_source_image_tags_source_images__id__tags_get"];
        put?: never;
        /**
         * Add Tag To Source Image
         * @description Add a tag to a source image. Creates tag if it doesn't exist.
         */
        post: operations["add_tag_to_source_image_source_images__id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-images/{id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Tag From Source Image
         * @description Remove a tag from a source image.
         */
        delete: operations["remove_tag_from_source_image_source_images__id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-images/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scan
         * @description Trigger album directory scan.
         */
        post: operations["trigger_scan_source_images_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gallery Images
         * @description List gallery images with pagination and optional tag filtering.
         */
        get: operations["list_gallery_images_gallery_images_get"];
        put?: never;
        /**
         * Create Gallery Image
         * @description Create a new gallery image with slots.
         */
        post: operations["create_gallery_image_gallery_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery-images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gallery Image
         * @description Get a single gallery image by ID with its slots.
         */
        get: operations["get_gallery_image_gallery_images__id__get"];
        /**
         * Update Gallery Image
         * @description Update a gallery image and its slots.
         */
        put: operations["update_gallery_image_gallery_images__id__put"];
        post?: never;
        /**
         * Delete Gallery Image
         * @description Delete a gallery image and decrement usage counts.
         */
        delete: operations["delete_gallery_image_gallery_images__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery-images/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gallery Image Tags
         * @description Get all tags for a gallery image.
         */
        get: operations["get_gallery_image_tags_gallery_images__id__tags_get"];
        put?: never;
        /**
         * Add Tag To Gallery Image
         * @description Add a tag to a gallery image. Creates tag if it doesn't exist.
         */
        post: operations["add_tag_to_gallery_image_gallery_images__id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery-images/{id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Tag From Gallery Image
         * @description Remove a tag from a gallery image.
         */
        delete: operations["remove_tag_from_gallery_image_gallery_images__id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tv-content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tv Content
         * @description List all TV content mappings with pagination.
         */
        get: operations["list_tv_content_tv_content_get"];
        put?: never;
        /**
         * Create Tv Content
         * @description Create a new TV content mapping.
         */
        post: operations["create_tv_content_tv_content_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tv-content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tv Content
         * @description Get a single TV content mapping by ID.
         */
        get: operations["get_tv_content_tv_content__id__get"];
        /**
         * Update Tv Content
         * @description Update a TV content mapping.
         */
        put: operations["update_tv_content_tv_content__id__put"];
        post?: never;
        /**
         * Delete Tv Content
         * @description Delete a TV content mapping.
         */
        delete: operations["delete_tv_content_tv_content__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tv-content/by-tv-id/{tv_content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tv Content By Tv Id
         * @description Get TV content mapping by TV content ID.
         */
        get: operations["get_tv_content_by_tv_id_tv_content_by_tv_id__tv_content_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Tv Content By Tv Id
         * @description Delete TV content mapping by TV content ID.
         */
        delete: operations["delete_tv_content_by_tv_id_tv_content_by_tv_id__tv_content_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tv-content/by-gallery-image/{gallery_image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tv Content By Gallery Image
         * @description Get TV content mapping by gallery image ID.
         */
        get: operations["get_tv_content_by_gallery_image_tv_content_by_gallery_image__gallery_image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Settings
         * @description Get all settings.
         */
        get: operations["get_all_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Setting
         * @description Get a setting by key.
         */
        get: operations["get_setting_settings__key__get"];
        /**
         * Update Setting
         * @description Update or create a setting.
         */
        put: operations["update_setting_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description List all tags, optionally filtered by name search.
         */
        get: operations["list_tags_tags_get"];
        put?: never;
        /**
         * Create Tag
         * @description Create a new tag or return existing if name already exists.
         */
        post: operations["create_tag_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tag
         * @description Get a single tag by ID.
         */
        get: operations["get_tag_tags__id__get"];
        /**
         * Update Tag
         * @description Update a tag.
         */
        put: operations["update_tag_tags__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Openapi
         * @description OpenAPI specification endpoint.
         */
        get: operations["openapi_openapi_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * GalleryImage
         * @description Model for gallery images (saved compositions).
         */
        GalleryImage: {
            /** Id */
            id?: number | null;
            /** Filename */
            filename: string;
            /** Filepath */
            filepath: string;
            /** Template Id */
            template_id: string;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * GalleryImageCreate
         * @description Gallery image creation request with slots.
         */
        GalleryImageCreate: {
            /** Filename */
            filename: string;
            /** Filepath */
            filepath: string;
            /** Template Id */
            template_id: string;
            /** Notes */
            notes?: string | null;
            /**
             * Slots
             * @default []
             */
            slots: components["schemas"]["ImageSlotCreate"][];
        };
        /**
         * GalleryImageWithSlots
         * @description Gallery image with slots.
         */
        GalleryImageWithSlots: {
            /** Id */
            id?: number | null;
            /** Filename */
            filename: string;
            /** Filepath */
            filepath: string;
            /** Template Id */
            template_id: string;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Slots
             * @default []
             */
            slots: components["schemas"]["ImageSlot"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageSlot
         * @description Model for image slots within gallery compositions.
         */
        ImageSlot: {
            /** Id */
            id?: number | null;
            /** Gallery Image Id */
            gallery_image_id: number;
            /** Slot Number */
            slot_number: number;
            /** Source Image Id */
            source_image_id?: number | null;
            /** Transform Data */
            transform_data?: {
                [key: string]: unknown;
            } | null;
            /** Metadata Snapshot */
            metadata_snapshot?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * ImageSlotCreate
         * @description Image slot creation model.
         */
        ImageSlotCreate: {
            /** Slot Number */
            slot_number: number;
            /** Source Image Id */
            source_image_id?: number | null;
            /** Transform Data */
            transform_data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RecalculateUsageResponse
         * @description Response model for usage count recalculation.
         */
        RecalculateUsageResponse: {
            /** Success */
            success: boolean;
            /** Total Images */
            total_images: number;
            /** Updated Count */
            updated_count: number;
            /** Negative Counts Corrected */
            negative_counts_corrected: number;
        };
        /**
         * ScanResponse
         * @description Response model for scan operation.
         */
        ScanResponse: {
            /** Scanned */
            scanned: number;
            /** Added */
            added: number;
            /** Updated */
            updated: number;
            /** Deleted */
            deleted: number;
        };
        /**
         * SettingValue
         * @description Setting value model.
         */
        SettingValue: {
            /** Value */
            value: unknown;
        };
        /**
         * Settings
         * @description Model for application settings.
         */
        Settings: {
            /** Id */
            id?: number | null;
            /** Key */
            key: string;
            /** Value */
            value: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * SettingsResponse
         * @description Response model for all settings.
         */
        SettingsResponse: {
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /**
         * SourceImage
         * @description Model for source images from albums directory.
         */
        SourceImage: {
            /** Id */
            id?: number | null;
            /** Filename */
            filename: string;
            /** Filepath */
            filepath: string;
            /** Date Taken */
            date_taken?: string | null;
            /**
             * Is Deleted
             * @default false
             */
            is_deleted: boolean;
            /**
             * Usage Count
             * @default 0
             */
            usage_count: number;
            /** Exif Metadata */
            exif_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * SourceImageResponse
         * @description Source image response model with computed is_used field.
         */
        SourceImageResponse: {
            /** Id */
            id?: number | null;
            /** Filename */
            filename: string;
            /** Filepath */
            filepath: string;
            /** Date Taken */
            date_taken?: string | null;
            /** Is Deleted */
            is_deleted: boolean;
            /** Usage Count */
            usage_count: number;
            /** Is Used */
            is_used: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * TVContentMapping
         * @description Model for mapping gallery images to TV content IDs.
         */
        TVContentMapping: {
            /** Id */
            id?: number | null;
            /** Gallery Image Id */
            gallery_image_id?: number | null;
            /** Tv Content Id */
            tv_content_id: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at?: string;
            /** Last Verified At */
            last_verified_at?: string | null;
            /**
             * Sync Status
             * @default pending
             */
            sync_status: string;
        };
        /**
         * Tag
         * @description Model for tags used to organize images.
         */
        Tag: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * TagCreate
         * @description Tag creation request model.
         */
        TagCreate: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /**
         * TagUpdate
         * @description Tag update request model.
         */
        TagUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * AddTagRequest
         * @description Request model for adding a tag.
         */
        routers__gallery_images__AddTagRequest: {
            /** Tag Name */
            tag_name: string;
            /** Tag Color */
            tag_color?: string | null;
        };
        /**
         * PaginatedResponse
         * @description Paginated response model.
         */
        routers__gallery_images__PaginatedResponse: {
            /** Items */
            items: components["schemas"]["GalleryImage"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /**
         * PaginatedResponse
         * @description Paginated response model.
         */
        routers__source_images__PaginatedResponse: {
            /** Items */
            items: components["schemas"]["SourceImageResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /**
         * PaginatedResponse
         * @description Paginated response model.
         */
        routers__tv_content__PaginatedResponse: {
            /** Items */
            items: components["schemas"]["TVContentMapping"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_source_images_source_images_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filter by usage status (true=used, false=unused, null=all) */
                used?: boolean | null;
                /** @description Comma-separated list of tag names to filter by */
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__source_images__PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_image_source_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceImage"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_image_source_images__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_image_source_images__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceImage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recalculate_usage_counts_source_images_recalculate_usage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecalculateUsageResponse"];
                };
            };
        };
    };
    get_source_image_tags_source_images__id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tag_to_source_image_source_images__id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["routers__gallery_images__AddTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tag_from_source_image_source_images__id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scan_source_images_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
        };
    };
    list_gallery_images_gallery_images_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Comma-separated list of tag names to filter by */
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__gallery_images__PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gallery_image_gallery_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GalleryImageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryImageWithSlots"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gallery_image_gallery_images__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryImageWithSlots"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gallery_image_gallery_images__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GalleryImageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryImageWithSlots"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gallery_image_gallery_images__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gallery_image_tags_gallery_images__id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tag_to_gallery_image_gallery_images__id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["routers__gallery_images__AddTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tag_from_gallery_image_gallery_images__id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tv_content_tv_content_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__tv_content__PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tv_content_tv_content_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TVContentMapping"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TVContentMapping"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tv_content_tv_content__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TVContentMapping"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tv_content_tv_content__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TVContentMapping"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TVContentMapping"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tv_content_tv_content__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tv_content_by_tv_id_tv_content_by_tv_id__tv_content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tv_content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TVContentMapping"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tv_content_by_tv_id_tv_content_by_tv_id__tv_content_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tv_content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tv_content_by_gallery_image_tv_content_by_gallery_image__gallery_image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gallery_image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TVContentMapping"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    get_setting_settings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingValue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_setting_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingValue"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: {
                /** @description Search tags by name prefix */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_tags__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_tags__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    openapi_openapi_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
